baseURL = "https://andreino01.github.io/" # Il tuo URL GitHub Pages
title = "La Ghironda"                     # Titolo del tuo sito
languageCode = "it-it"                   # Imposta la lingua italiana
theme = "soho"                           # Nome della cartella del tema Soho
enableInlineShortcodes = true            # Utile per alcuni shortcodes
enableEmoji = true                       # Se vuoi usare emoji

summarylength = 20 # Lunghezza del riassunto (numero di parole) per le anteprime

# PARAMETRI SPECIFICI DEL TEMA SOHO E GLOBALI DEL SITO
[params]
  author = "La Ghironda"
  
  # Immagine del profilo/logo per Soho
  # Assicurati che l'immagine esista in static/images/logo_ghironda.png (o il percorso che scegli)
  profilePicture = "images/logo_laghironda.png"

  copyright = "© Associazione La Ghironda" # Puoi aggiungere l'anno o personalizzare
  # license = "CC BY-NC-SA 4.0" # Esempio se vuoi una licenza
  # licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

  # Colore del tema personalizzato (opzionale)
  #themeColor = "#003366" # Il tuo blu, se vuoi provare a sovrascrivere quello di Soho

  # File CSS e JS personalizzati (creali in static/css/ e static/js/ se li usi)
  customCss = ["css/custom_laghironda.css"]
  # customJs = ["js/custom_laghironda.js"]

  # Icone Social (verifica come Soho le gestisce e se include Font Awesome)
  [[params.socialIcons]]
    icon = "fab fa-facebook-f" # Richiede Font Awesome
    title = "Facebook"
    url = "https://facebook.com/" # SOSTITUISCI

  [[params.socialIcons]]
    icon = "fab fa-instagram" # Richiede Font Awesome
    title = "Instagram"
    url = "https://www.instagram.com/_laghironda" # SOSTITUISCI

# MENU PRINCIPALE
[menu]
#  [[menu.main]]
#    name = "Home"
#    identifier = "home"
 #   weight = 10
 #    url = "/home/"

  [[menu.main]]
    identifier = "chi-siamo"
    name = "Chi Siamo"
    url = "/chi-siamo/"
    weight = 20

  [[menu.main]]
    identifier = "le-nostre-attivita"
    name = "Le Nostre Attività"
    url = "/le-nostre-attivita/"
    weight = 25

  [[menu.main]]
    identifier = "eventi"
    name = "Eventi"
    url = "/eventi/"
    weight = 30

  [[menu.main]]
    identifier = "sostienici"
    name = "Sostienici"
    url = "/sostienici/"
    weight = 40

  [[menu.main]]
    identifier = "contatti"
    name = "Contatti"
    url = "/contatti/"
    weight = 50

# TASSOMOMIE (opzionale per ora se non hai un blog)
[taxonomies]
  category = "categorie"
  series = "serie"
  tag = "tag"

# MARKUP CONFIGURATION (Fondamentale per iframe e codice)
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = true # Soho potrebbe gestire gli stili del codice; se no, imposta a false e fornisci CSS
    style = "monokai" # Stile per l'highlighting del codice

  [markup.goldmark.renderer]
    unsafe = true # NECESSARIO per l'iframe del Google Calendar