backend:
  name: github
  repo: andreino01/andreino01.github.io
  branch: main
  auth_scope: repo
  client_id: Ov23liMpW4ognFEuKbnz
  

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
